service: wankang-server

plugins:
  - serverless-plugin-typescript 

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'